# Generated by Django 3.2.5 on 2022-05-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='sub_tasks', to='core.Task'),
        ),
    ]
