# Generated by Django 3.2.5 on 2022-05-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_assigned_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='assigned_tasks',
        ),
        migrations.AddField(
            model_name='team',
            name='assigned_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task'),
        ),
    ]
