# Generated by Django 3.2.5 on 2022-05-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220505_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('assigned', 'assigned'), ('completed', 'completed'), ('created', 'created')], default='created', max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
