# Generated by Django 3.2.5 on 2022-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220506_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('created', 'created'), ('assigned', 'assigned')], default='created', max_length=30),
        ),
    ]
