# Generated by Django 3.2.5 on 2022-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220506_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='sequence',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pending_tasks',
            field=models.ManyToManyField(blank=True, related_name='team_pending_tasks', to='core.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('created', 'created'), ('assigned', 'assigned')], default='created', max_length=30),
        ),
    ]
