# Generated by Django 3.2.5 on 2022-05-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220506_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('assigned', 'assigned'), ('completed', 'completed')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
