# Generated by Django 3.2.5 on 2022-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220506_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('assigned', 'assigned'), ('created', 'created')], default='created', max_length=30),
        ),
    ]
